GET http://localhost:3000/subscribers


###

GET http://localhost:3000/subscribers/
65f74fa5c53b875807184bb3e

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}